// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _222LTC02_2050531200110_NguyenDucCuong.Data;

#nullable disable

namespace _222LTC02_2050531200110_NguyenDucCuong.Migrations
{
    [DbContext(typeof(_222LTC02_2050531200110_NguyenDucCuongContext))]
    partial class _222LTC02_2050531200110_NguyenDucCuongContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_222LTC02_2050531200110_NguyenDucCuong.Models.GioHang", b =>
                {
                    b.Property<int>("GioHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GioHangId"), 1L, 1);

                    b.Property<int>("NguoiMuaId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ThucPhamId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GioHangId");

                    b.HasIndex("NguoiMuaId");

                    b.HasIndex("ThucPhamId");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("_222LTC02_2050531200110_NguyenDucCuong.Models.NguoiMua", b =>
                {
                    b.Property<int>("NguoiMuaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiMuaId"), 1L, 1);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguoiMuaId");

                    b.ToTable("NguoiMua");
                });

            modelBuilder.Entity("_222LTC02_2050531200110_NguyenDucCuong.Models.ThucPham", b =>
                {
                    b.Property<int>("ThucPhamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThucPhamId"), 1L, 1);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ThucPhamId");

                    b.ToTable("ThucPham");
                });

            modelBuilder.Entity("_222LTC02_2050531200110_NguyenDucCuong.Models.GioHang", b =>
                {
                    b.HasOne("_222LTC02_2050531200110_NguyenDucCuong.Models.NguoiMua", null)
                        .WithMany("GioHangs")
                        .HasForeignKey("NguoiMuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_222LTC02_2050531200110_NguyenDucCuong.Models.ThucPham", "ThucPham")
                        .WithMany("GioHangs")
                        .HasForeignKey("ThucPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThucPham");
                });

            modelBuilder.Entity("_222LTC02_2050531200110_NguyenDucCuong.Models.NguoiMua", b =>
                {
                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("_222LTC02_2050531200110_NguyenDucCuong.Models.ThucPham", b =>
                {
                    b.Navigation("GioHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
